spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: false
  liquibase:
    enabled: true
logging:
  level:
    farm.giggle: DEBUG
    org.springframework: ERROR
    org.springframework.security: ERROR