spring:
  profiles:
    active: ${ACTIVE_PROFILE}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED}

yt2rss:
  downloadablePortion: 9
  channel-page:
    sort-order: title
    number-entries-on-page: 5