spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect