spring:
  profiles:
    active: ${ACTIVE_PROFILE}

  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            client-id: ${OA2_YANDEX_CLIENT_ID}
            client-secret: ${OA2_YANDEX_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
          github:
            client-id: ${OA2_GITHUB_CLIENT_ID}
            client-secret: ${OA2_GITHUB_CLIENT_SECRET}
          google:
            client-id: ${OA2_GOOGLE_CLIENT_ID}
            client-secret: ${OA2_GOOGLE_CLIENT_SECRET}
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
            user-info-authentication-method: header
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

yt2rss:
  downloadablePortion: 9
  channel-page:
    sort-order: title
    number-entries-on-page: 5