spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_PROD}:${DB_PORT_PROD}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  liquibase:
    enabled: true