spring:
  profiles:
    active: prod
  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            client-id: 
            client-secret: 
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
          github:
            client-id: 
            client-secret: 
          google:
            client-id: 
            client-secret: 
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
            user-info-authentication-method: header
  datasource:
    url: jdbc:postgresql://localhost:5433/y2rssdb
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
yt2rss:
  downloadablePortion: 9
  channel-page:
    sort-order: title
    number-entries-on-page: 5
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG

