spring:
  profiles:
    active: prod
  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            client-id: 5c3a7947af2340f9862fe8b70e5ac16d
            client-secret: 75c8b5d89137499cb1eae908dd3beefa
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
          github:
            client-id: c22df1cbf829963ee017
            client-secret: de95a9bc5c76e6980510ca6839ca7d0299b4b67d
          google:
            client-id: 325803809182-01cotg0kfqmf7lvgk80sqlg6ea5gc5df.apps.googleusercontent.com
            client-secret: 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
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
            user-info-authentication-method: header
  datasource:
    url: jdbc:postgresql://localhost:5433/y2rssdb
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
yt2rss:
  downloadablePortion: 9
  channel-page:
    sort-order: title
    number-entries-on-page: 5
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG

