spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            client-id: ${OA2_YANDEX_CLIENT_ID}
            client-secret: ${OA2_YANDEX_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
          github:
            client-id: ${OA2_GITHUB_CLIENT_ID}
            client-secret: ${OA2_GITHUB_CLIENT_SECRET}
          google:
            client-id: ${OA2_GOOGLE_CLIENT_ID}
            client-secret: ${OA2_GOOGLE_CLIENT_SECRET}
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
            user-info-authentication-method: header
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: false
logging:
  level:
    farm.giggle: DEBUG
    org.springframework: ERROR
    org.springframework.security: ERROR