spring:
  datasource:
    username: y2rss
    password: 111111
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate