spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_LOCAL}:${DB_PORT_LOCAL}/y2rssdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: false
  liquibase:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG