spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c22df1cbf829963ee017
            client-secret: de95a9bc5c76e6980510ca6839ca7d0299b4b67d
          google:
            client-id: 325803809182-01cotg0kfqmf7lvgk80sqlg6ea5gc5df.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:postgresql://localhost:5433/y2rssdb
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
yt2rss:
  downloadablePortion: 9
  channel-page:
    sort-order: title
    number-entries-on-page: 5


